


services:
  
  backend: 
    image: go-rest-api
    build: .
    ports:
      - "8000:${PORT}"    
    depends_on: 
      - db

    
  
  db:
    image: postgres:17
    restart: always 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

    volumes:
      - db-data:/var/lib/postgresql/data
      - .\migrations\000_init_scheme.sql:/docker-entrypoint-initdb.d/init.sql

  
volumes:
  db-data: